# Generated by Django 5.2.4 on 2025-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='Recipe.ingredient'),
        ),
    ]
